<?php
$l['number'] 						= 'Referencia';
$l['date'] 							= 'Fecha';
$l['due'] 							= 'Fecha de vencimiento';
$l['to'] 							= 'Facturacion a';
$l['from'] 							= 'Nuestra informacion ';
$l['product'] 						= 'Producto';
$l['amount'] 						= 'Cantidad';
$l['price'] 						= 'Precio';
$l['discount'] 						= 'Descuento';
$l['vat'] 							= 'Impuestos';
$l['total'] 						= 'Total de';
$l['page'] 							= 'Pagina';
$l['page_of'] 						= 'de';
?>